### PR TITLE
Converter and interactive tree

### PR DESCRIPTION
**Pull request by robinschmid**
Some additions:
- a python script to convert the owl ontology to json
- the json file
- two versions of an interactive tree
a. ontology only
b. ontology with MASST results

### CODE REVIEW

**Comment by ka-west** [comment]
@robinschmid I spot-checked some of the values and it seems that the higher up ontology terms don't match with the results file. For example: fleshy fruit in the MASST results is `group_size=861`, `matched_size=75`, `occurence_fraction=0.087` but in the tree is `group_size=2990`, `matched_size=296`, `occurence_fraction=0.099`. Can we make sure the values are read directly from the MASST results?

**Comment by ka-west** [comment]
One other really small thing, can you please round the occurrence fraction to 3 or 4 decimal places? Just so it looks a bit cleaner. Thanks!!

**Comment by robinschmid** [comment]
Yes. Sounds good. Need to recheck the file format maybe I misinterpreted it.

**Comment by robinschmid** [comment]
@ka-west 
- updated the MASST results import and it is correct now. 
- fixed number format to 3 decimal figures

**Pull request merged**
